routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function() {
    return view('home');
})->name('home');



Route::middleware('guest')->group(function() {
    Route::get('/login', [AuthController::class, 'loginIndex'])->name('login');
    Route::post('/login', [AuthController::class, 'loginStore'])->name('login.store');

    Route::get('/register', [AuthController::class, 'registerIndex'])->name('register');
    Route::post('/register', [AuthController::class, 'registerStore'])->name('register.store');
});

Route::middleware('auth')->group(function() {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::prefix('/user')->middleware('auth')->group(function() {
    Route::get('/show', [UserController::class, 'show'])->name('user.show');

    Route::get('/update', [UserController::class, 'edit'])->name('user.edit');
    Route::post('/update', [UserController::class, 'update'])->name('user.update');

    Route::get('/update-password', [UserController::class, 'editPassword'])->name('user.editPassword');
    Route::post('/update-password', [UserController::class, 'updatePassword'])->name('user.updatePassword');

    Route::delete('/delete', [UserController::class, 'destroy'])->name('user.delete');
});

Route::prefix('/posts')->middleware('auth')->name('posts.')->group(function() {
    Route::get('/search', [PostController::class, 'search'])->name('search');

    Route::get('/', [PostController::class, 'index'])->name('index');

    Route::get('/create', [PostController::class, 'create'])->name('create');
    Route::post('/store', [PostController::class, 'store'])->name('store');

    Route::get('/show/{post}', [PostController::class, 'show'])->name('show');

    Route::get('/show-mine', [PostController::class, 'showMine'])->name('showMine');
    Route::get('/edit/{post}', [PostController::class, 'edit'])->name('edit');
    Route::post('/update/{post}', [PostController::class, 'update'])->name('update');

    Route::delete('/delete/{post}', [PostController::class, 'destroy'])->name('delete');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'body',
    ];

    public function author() 
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Actions\Post\EditPostAction;
use App\Actions\Post\StorePostAction;
use App\Helpers\AlertHelper;
use App\Http\Requests\Post\SearchPostRequest;
use App\Http\Requests\Post\StorePostRequest;
use App\Http\Requests\Post\EditPostRequest;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function search(SearchPostRequest $request)
    {
        $param = $request->validated()['param'];

        $posts = Post::query()
            ->select('posts.id', 'posts.title', 'users.name', 'users.surname')
            ->join('users', 'user_id', '=', 'users.id')
            ->where('posts.title', 'like', "%{$param}%")
            ->orWhere('users.name', 'like', "%{$param}%")
            ->orWhere('users.surname', 'like', "%{$param}%")
            ->orderBy('title')
            ->paginate(15);

        return view('posts.index', [ 'posts' => $posts ]);
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = Post::select('posts.id', 'title', 'users.name', 'users.surname')
            ->join('users', 'user_id', '=', 'users.id')
            ->orderBy('title')
            ->paginate(15);

        // dd($posts);

        return view('posts.index', [ 'posts' => $posts ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePostRequest $request, StorePostAction $storePost, AlertHelper $alert)
    {
        $storePost($request->validated(), new Post);
        
        $alert('Пост успешно создан');
        return redirect(route('posts.create'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        return view('posts.show', ['post' => $post, 'previous_page' => url()->previous()]);
    }

    public function showMine()
    {
        $mine_posts = Post::select('id', 'title')
            ->where('user_id', '=', Auth::id())
            ->orderBy('title')
            ->paginate(15);

        return view('posts.showMine', ['posts' => $mine_posts]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        return view('posts.edit', ['post' => $post, 'previous_page' => url()->previous()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EditPostRequest $request, Post $post, EditPostAction $editPost)
    {
        $editPost($request->validated(), $post);

        return redirect(route('posts.showMine'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect(url()->previous());
    }
}

resources/views/posts/create.blade.php
@extends('layouts.center')

@section('page.title', __('Создать пост'))

@section('center.content')
  <x-card>
    <x-card-header>{{ __('Создать пост') }}</x-card-header>

    <div class="card-body">
      <form action={{ route('posts.store') }} method="post">
        @csrf

        <x-input name="title">{{ __('Заголовок') }}</x-input>
        <x-error name="title" />
        <x-text-area name="body">{{ __('Пост') }}</x-text-area>
        <x-error name="body" />

        <x-button type="sumbit">{{ __('Создать') }}</x-button>
      </form>
      
    </div>
  </x-card>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.center')

@section('page.title', 'Edit post')

@section('center.content')
  <x-card>
    <x-card-header>
      {{ __('Редактировать пост') }}

      <x-slot name="right">
        <a href="{{ $previous_page }}">{{ __('Назад') }}</a>
      </x-slot>
    </x-card-header>
    
    <div class="card-body">
      <form action="{{ route('posts.update', $post->id) }}" method="post">
        @csrf

        <input type="text" name="title" placeholder="{{ $post->title }}" class="form-control mb-3">
        <textarea name="body" rows="3" placeholder="{{ $post->body }}" class="form-control mb-3"></textarea>

        <x-button type="submit">{{ __('Отправить') }}</x-button>
      </form>
    </div>
  </x-card>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.center')

@section('page.title', __('Posts'))

@section('center.content')
  <x-card>
    <x-card-header>
      {{ __('Посты') }}
    </x-card-header>

    <div class="card-body">
      <form action="{{ route('posts.search') }}" method="get">
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="param" placeholder="{{ __('поиск...') }}" aria-label="Recipient's username" aria-describedby="button-addon2">
          <button class="btn btn-outline-primary" type="sumbit" id="button-addon2">{{ __('Поиск') }}</button>
        </div>
      </form> 

      <ul class="list-group mb-3">
        @foreach ($posts as $post)
          <x-list-item href="{{ route('posts.show', $post->id) }}">

            <x-list-item-body>
              <x-slot name="header">
                {{ __('Название:') }}
              </x-slot>

              {{ $post->title }}
            </x-list-item-body>
            
            <x-list-item-body>
              <x-slot name="header">
                {{ __('Автор:') }}
              </x-slot>

              {{ $post->name.' '.$post->surname }}

              <x-slot name="right">
                <a href="{{ route('posts.show', $post->id) }}">{{ __('Перейти') }}</a>
              </x-slot>
            </x-list-item-body>

          </x-list-item>
        @endforeach
      </ul>
      
      {{$posts->links()}}
    </div>
  
  </x-card>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.center')

@section('page.title', $post->title)

@section('center.content')
  <x-card>
    <x-card-header>
      {{ $post->title }}

      <x-slot name="right">
        <a href="{{ $previous_page }}">{{ __('Назад') }}</a>
      </x-slot> 
    </x-card-header>

    <div class="card-body">
      {{ $post->body }}

      <a href="{{ route('posts.edit', $post->id) }}">{{ __('Редактировать') }}</a>
    </div>
  </x-card>
@endsection

resources/views/posts/showMine.blade.php
@extends('layouts.center')

@section('page.title', __('Mine posts'))

@section('center.content')
  <x-card>
    <x-card-header>
      {{ __('Мои посты') }}
    </x-card-header>

    <div class="card-body">
      <ul class="list-group mb-3">
        @foreach ($posts as $post)
          <x-list-item href="{{ route('posts.show', $post->id) }}">

            <x-list-item-body>
              <x-slot name="header">
                {{ __('Название:') }}
              </x-slot>

              {{ $post->title }}

              <x-slot name="right">
                <div class="dropdown">
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ route('posts.show', $post->id) }}">{{ __('Перейти') }}</a></li>
                    <li><a class="dropdown-item" href="{{ route('posts.edit', $post->id) }}">{{ __('Редактировать') }}</a></li>
                    <li><x-open-popup-button class="dropdown-item text-danger" data-bs-target="#delete_post">{{ __('Удалить') }}</x-open-popup-button></li>
                  </ul>
                </div>
              </x-slot>
            </x-list-item-body>
      
          </x-list-item>

          <x-popup id="delete_post">
            {{ __('Вы действительно хотите удалить пост?') }}
        
            <x-slot name="buttons">
              <form action={{ route('posts.delete', $post->id) }} method="post">
                @csrf
                @method('delete')
                <x-button type="submit">{{ __('Подтвердить') }}</x-button>
              </form>
            </x-slot>
          </x-popup>
        @endforeach
      </ul>
      
      {{$posts->links()}}
    </div>
  
  </x-card>
@endsection