routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function() {
    return view('home');
})->name('home');



Route::middleware('guest')->group(function() {
    Route::get('/login', [AuthController::class, 'loginIndex'])->name('login');
    Route::post('/login', [AuthController::class, 'loginStore'])->name('login.store');

    Route::get('/register', [AuthController::class, 'registerIndex'])->name('register');
    Route::post('/register', [AuthController::class, 'registerStore'])->name('register.store');
});

Route::middleware('auth')->group(function() {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::prefix('/user')->middleware('auth')->group(function() {
    Route::get('/show', [UserController::class, 'show'])->name('user.show');

    Route::get('/update', [UserController::class, 'edit'])->name('user.edit');
    Route::post('/update', [UserController::class, 'update'])->name('user.update');

    Route::get('/update-password', [UserController::class, 'editPassword'])->name('user.editPassword');
    Route::post('/update-password', [UserController::class, 'updatePassword'])->name('user.updatePassword');

    Route::delete('/delete', [UserController::class, 'destroy'])->name('user.delete');
});

Route::prefix('/posts')->middleware('auth')->name('posts.')->group(function() {
    Route::get('/search', [PostController::class, 'search'])->name('search');

    Route::get('/', [PostController::class, 'index'])->name('index');

    Route::get('/create', [PostController::class, 'create'])->name('create');
    Route::post('/store', [PostController::class, 'store'])->name('store');

    Route::get('/show/{post}', [PostController::class, 'show'])->name('show');

    Route::get('/show-mine', [PostController::class, 'showMine'])->name('showMine');
    Route::get('/edit/{post}', [PostController::class, 'edit'])->name('edit');
    Route::post('/update/{post}', [PostController::class, 'update'])->name('update');

    Route::delete('/delete/{post}', [PostController::class, 'destroy'])->name('delete');
});

resources/views/includes/alert.blade.php
@if($alert = session()->pull('alert'))
    <div class="alert alert-success mb-0 rounded-0 text-center small py-2">
        {{ __($alert) }}
    </div>
@endif

resources/views/includes/footer.blade.php
<footer class="py-3 border-t-2 text-center">
  {{ config('app.name', 'Laravel') }}
</footer>

resources/views/includes/header.blade.php
@php
  function isActive(string $link): string
  {
    if (Route::is($link)) return 'active';
    else return ''; 
  }
@endphp

<nav class="navbar navbar-expand-lg bg-body-tertiary bg">
  <div class="container">

    <a class="navbar-brand" href={{ route('home') }}>{{ __(config('app.name', 'Laravel')) }}</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link {{ isActive('home') }}" aria-current="page" href={{ route('home') }}>{{ __('Home') }}</a>
        </li>

        @auth
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ __('Посты') }}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href={{ route('posts.index') }}>{{ __('Просмотреть все') }}</a></li>
              <li><a class="dropdown-item" href={{ route('posts.showMine') }}>{{ __('Просмотреть мои') }}</a></li>
              <li><a class="dropdown-item" href={{ route('posts.create') }}>{{ __('Создать') }}</a></li>
              {{-- <li><hr class="dropdown-divider"></li> --}}
            </ul>
          </li>
        @endauth
  
      </ul>

      <ul class="navbar-nav">
        @if (Auth::user())
          <li><a href={{ route('user.show') }} class="nav-link">&#128578; {{ __(Auth::user()->name) }}</a></li>
        @else
          <li><a href={{ route('register') }} class="nav-link border-end border-3 {{ isActive('register') }}">{{ __('Регистрация') }}</a></li>
          <li><a href={{ route('login') }} class="nav-link {{ isActive('login') }}">{{ __('Вход') }}</a></li>
        @endif
      </ul>
    </div>
  </div>
</nav>